### ISSUE TITLE
write blog post on SeaGL 2020 tech stack

### ISSUE THREAD

**Issue by altsalt** [SeaGL/organization#229] opened 2020-12-21 21:19 UTC
there and back again and again and again

[ ] include release of codebase(s)

## notes from retrospective
- why did we decide to make this
  - values
  - why not just use an easy commercial solution
  - alternatives considered
- initial architectural decisions
- building an excellent team
- iterating on decisions until something that "work"
  - what did we rule out?
- last week discoveries...
- the conference itself
  - list of tools
    - what did we use
    - what did we build
- pitfalls/lessons learned
- looking forward/links to code

**Comment by AndrewKvalheim** [comment] 2021-12-09 02:20
Duplicate of #39

**Closed by AndrewKvalheim** 2021-12-09 02:20 UTC
Labels: Tech
